"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import metrics as shared_metrics
from typing import Optional



@dataclasses.dataclass
class GetMetricsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    metrics: Optional[shared_metrics.Metrics] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

