"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import api as shared_api
from typing import Optional



@dataclasses.dataclass
class ListAPIsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    ap_is: Optional[dict[str, shared_api.API]] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

